HTML New York Times project
JuanDavid31/nyc-copy pull request #1
Opened 2021-01-13 20:25 UTC by EroAuditore

## Milestones
### Project setup & assets
Setting up a repository, files, text, images, icons, colors, and fonts.
### Website skeleton
Create an HTML skeleton with the header, footer, article, navigation, aside, etc.
### Markup & simple styling 
Finish styling fonts and colors
### First complete version 
Use flexbox, CSS grid, and floating elements for position inside the header, footer, articles, etc.
### Final touches
Correct bugs and some details in the CCS style
### Deployment & documentation
Deploy Github pages, Create the read me file, check for linter errors, and create a pull request

2021-01-13 22:04 UTC, bertil291utn requested changes
# **Status:** Changes requested 🟠 
<p align="center"> <img src="https://i.cubeupload.com/4HbSFK.jpg" alt="image" width="60" /> <br><strong>Not yet</strong> </p>

# Hey guys, you've been doing a great job, and also I hope you enjoyed coding.

### Your work is amazing you master it GitHub Flow you have a professional README file. 

However, in order to accomplish as the actual page, you required to do these changes, listed below:
## Specific requirements 
### Navigation Bar
- It has a "Hamburger button", a search icon and a link with text on the leftmost side ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/positioning_and_floating_requirements.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/))
  - In the navbar section add this text should be a link  
![image](https://user-images.githubusercontent.com/24902525/104513302-711f7900-55bd-11eb-8651-6646a8015935.png)
- [x] The NY Times logo should be a image embedded ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/positioning_and_floating_requirements.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/))
* [ ] The NY Times logo should be a link ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/positioning_and_floating_requirements.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/))
### Bottom section
- Add this section and don't forget to add anchor tags to each article 
![image](https://user-images.githubusercontent.com/24902525/104513691-0884cc00-55be-11eb-9c75-ec5b25af70ce.png)
### Theory  of inflation section
- Add large font size to the title
- Use `display: grid;` rule to display this grid section, because this way avoid using position absolute, the reason why the images are overlapping 
![image](https://user-images.githubusercontent.com/24902525/104514137-c3ad6500-55be-11eb-8266-24088c188f4b.png)


### FILE: README.md
- Update screenshot section, updating the directory screenshot path, use this line `![screenshot](img/readme.png)`
- Elaborate getting started section, explaining in every detailed way how to clone, and start this project 

### Summary

-  Don't forget to work with inline comments below this comment box, about CSS rules
-  Complete a section is missing 
- Work on the navbar section, there some reuqirments that are missing 

***

Guys work in the requested changes above and request another review.
Good luck. 

> “Never stop, never conform until what is good becomes even better, and what’s better becomes excellent.”

2021-01-13 22:04 UTC, bertil291utn commented on style/index.css
> +}
## Shorthand Properties Rule[1]
>Shorthand properties allow you to set the rules of numerous CSS properties simultaneously. Using a shorthand property will shrink your CSS and increase readability.

For instance, instead of using margin-top, margin-right, margin-bottom, margin-left separately you can simply use just one line.
 
 - [ ] Make in just one border line 
 ```css
 margin: auto 0 auto 10px;
 ```
<hr>

_[1] [Good and bad  CSS practices](https://speckyboy.com/good-bad-css-practices/)_

2021-01-13 22:04 UTC, bertil291utn commented on style/index.css
> +  margin-top: 30px;
## Shorthand Properties Rule[1]
>Shorthand properties allow you to set the rules of numerous CSS properties simultaneously. Using a shorthand property will shrink your CSS and increase readability.

For instance, instead of using margin-top, margin-right, margin-bottom, margin-left separately you can simply use just one line.
 
 - [ ] Make in just one border line 
 ```css
  border-top: 1px solid #ebebeb;
 ```
<hr>

_[1] [Good and bad  CSS practices](https://speckyboy.com/good-bad-css-practices/)_

2021-01-14 23:43 UTC, voscarmv approved these changes
# Project status: Approved ✨ 😎👍 💯 ✔️
### You may merge this branch and move forward ⛙🛣

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

2021-01-15 00:05 UTC, merged